name = "test_mcp9808_i2c"
description = "test for the mcp9808_i2c crate"
version = "0.9.0"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
licenses = "BSD-3-Clause"
website = "https://github.com/hgrodriguez/mcp9808_i2c"
tags = []

[[depends-on]]
rp2040_hal = "^2"
pico_bsp = "^2"
aunit = "^24"

[[pins]]
mcp9808_i2c = { path='..' }

[gpr-set-externals]
AUNIT_RUNTIME = "zfp-cross"

[build-profiles]
"*" = "validation"
usb_embedded = "release"
atomic = "release"
aunit = "release"
